graphics:
    matplotlib:
      # key:values under rcParams are used to update matplotlib.rcParams
      rcParams: 
        'figure.dpi': 160.0
        # this ensures text in plots is exported as text objects
        svg.fonttype: "none"graphics:
    matplotlib:
      # key:values under rcParams are used to update matplotlib.rcParams
      rcParams: 
        'figure.dpi': 160.0
        # this ensures text in plots is exported as text objects
        svg.fonttype: "none"
figure_saving:
      # these arguments are passed to matplotlib.pyplot.savefig
      # https://matplotlib.org/api/_as_gen/matplotlib.pyplot.savefig.html
      format: svg
      dpi: 300
      bbox_inches: "tight"
    close_saved_figures: True
