graphics:
    matplotlib:
      # key:values under rcParams are used to update matplotlib.rcParams
      rcParams: 
        'figure.dpi': 300.0
        # this ensures text in plots is exported as text objects
        svg.fonttype: "none"
