name: IMAC
channels:
- conda-forge
dependencies:
- matplotlib-base
- pandas
- scipy
- numpy
- ipywidgets
- jupyterlab>=3.1
- voila>=0.2.11
graphics:
    matplotlib:
      backend: TkAgg # Agg
      # key:values under rcParams are used to update matplotlib.rcParams
      rcParams: 
        figure.dpi: 160
        # this ensures text in plots is exported as text objects
        svg.fonttype: "none"
